

function mudaFoto(foto) {
    document.getElementById("icone").src = foto;
}

function mudaNome(name) {
    document.getElementById("name").innerHTML = name;
}


function mudaPT(){
    document.getElementById("titulo").innerHTML = 'Poltica de Privacidade'
    document.getElementById("texto").innerHTML = 'A política de privacidade (ou declaração de política de privacidade) é o documento por meio do qual a pessoa física ou jurídica que mantém um site ou aplicativo expõe e explica a todos os interessados a forma como os dados pessoais dos usuários da plataforma serão tratados. O assunto é regulamentado, no Brasil, principalmente pela Lei Geral de Proteção de Dados Pessoais (LGPD), lei que estabeleceu uma série de exigências àqueles que realizam operações de tratamento de dados pessoais. A lei se aplica: se a operação de tratamento é realizada no território nacional; se a atividade de tratamento tem por objetivo a oferta de produtos ou serviços ou o tratamento de dados de indivíduos localizados no território nacional; se os dados pessoais são coletados no território nacional. Pela lei, dado pessoal é qualquer informação relacionada a pessoa identificada ou identificável. A expressão "tratamento de dados pessoais" abrange praticamente tudo aquilo que se pode fazer com estes dados, como as atividades de coleta, produção, recepção, classificação, utilização, acesso, reprodução, transmissão, distribuição, processamento, arquivamento, armazenamento, eliminação, avaliação ou controle da informação, modificação, comunicação, transferência, difusão ou extração. Entre as obrigações que a lei impõe a quem realiza qualquer destas atividades, está a de ser transparente. Dessa forma, todo aquele que trata dados pessoais, incluindo os mantenedores de sites ou aplicativos, deve informar os titulares dos referidos dados, por exemplo, acerca da forma como são utilizados e dos motivos pelos quais são tratados. Por meio do presente modelo, será possível, dentre outros: informar ao usuário do site ou aplicativo quem é o controlador dos dados pessoais, ou seja, quem é a pessoa física ou jurídica que decide o que se faz com os dados coletados, armazenados ou, de qualquer outra forma, utilizados; informar ao usuário do site ou aplicativo quais são os dados pessoais coletados e utilizados pelo site ou aplicativo, explicitando os momentos nos quais as coletas são realizadas e as finalidades para as quais os dados são utilizados; informar ao usuário quais são seus direitos e as formas pelas quais pode exercê-los;'
}

function mudaEN(){
    document.getElementById("titulo").innerHTML = 'Privacy policy'
    document.getElementById("texto").innerHTML = 'The privacy policy (or privacy policy statement) is the document through which the natural or legal person who maintains a website or application exposes and explains to all interested parties how the personal data of users of the platform will be treated. The matter is regulated, in Brazil, mainly by the General Law of Protection of Personal Data (LGPD), a law that established a series of requirements to those who carry out operations of processing personal data. The law applies: if the treatment operation is carried out in the national territory; whether the processing activity is aimed at offering products or services or processing data from individuals located in the national territory; whether personal data is collected in the national territory. By law, personal data is any information related to an identified or identifiable person. The term "processing of personal data" covers practically everything that can be done with this data, such as the activities of collection, production, reception, classification, use, access, reproduction, transmission, distribution, processing, archiving, storage, disposal, evaluation or control of information, modification, communication, transfer, dissemination or extraction. Among the obligations that the law imposes on those who carry out any of these activities, is that of being transparent. Accordingly, anyone who treats personal data, including website or application maintainers, must inform the holders of such data, for example, about the way they are used and the reasons for which they are treated. Through this model, it will be possible, among others: to inform the user of the website or application who is the controller of personal data, that is, who is the natural or legal person who decides what to do with the data collected, stored or , in any other way, used; inform the user of the website or application what personal data is collected and used by the website or application, explaining the moments in which the collections are made and the purposes for which the data are used; inform the user what their rights are and the ways in which they can exercise them;'
}